apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: auth-test
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: master

  components:
    - name: logonapp
      src: .
      replicas: 2

      #publicPort: http
      ports:
       - name: http
         port: 80
      public: true

