apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: auth-test
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod

  components:

    - name: logonapp
       environmentConfig:
        - environment: prod
          replicas: 1
        - environment: dev
          replicas: 1
      src: .
      publicPort: http
      ports:
       - name: http
         port: 80
      public: true
      