apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: auth-test
spec:
  build:
    secrets:
      - SECRET_1
      - SECRET_2
  environments:
    - name: dev
      build:
        from: master
    
  components:
    - name: logonapp
      src: .
      replicas: 1

      
      ports:
       - name: http
         port: 80
      public: true

