apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: authtest
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: logonapp
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 5000
